"""Add abuse and consequence system models

Revision ID: 4d3afdb01e1f
Revises: d0085f6ca55d
Create Date: 2026-01-06 20:09:51.687725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3afdb01e1f'
down_revision: Union[str, Sequence[str], None] = 'd0085f6ca55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
