"""Add performance indexes and relationships

Revision ID: 4f5d681548db
Revises: 525f6b38b398
Create Date: 2026-01-06 11:00:51.486999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5d681548db'
down_revision: Union[str, Sequence[str], None] = '525f6b38b398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_health_conditions_health_record_id'), 'health_conditions', ['health_record_id'], unique=False)
    op.create_index(op.f('ix_health_medications_health_record_id'), 'health_medications', ['health_record_id'], unique=False)
    op.create_index(op.f('ix_health_records_npc_id'), 'health_records', ['npc_id'], unique=True)
    op.create_index(op.f('ix_health_visits_health_record_id'), 'health_visits', ['health_record_id'], unique=False)
    op.create_index('idx_npc_location', 'npcs', ['map_x', 'map_y'], unique=False)
    op.create_index(op.f('ix_npcs_scenario_key'), 'npcs', ['scenario_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npcs_scenario_key'), table_name='npcs')
    op.drop_index('idx_npc_location', table_name='npcs')
    op.drop_index(op.f('ix_health_visits_health_record_id'), table_name='health_visits')
    op.drop_index(op.f('ix_health_records_npc_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_medications_health_record_id'), table_name='health_medications')
    op.drop_index(op.f('ix_health_conditions_health_record_id'), table_name='health_conditions')
    # ### end Alembic commands ###
