"""Add inference_rules table for data fusion engine

Revision ID: d0085f6ca55d
Revises: 4f5d681548db
Create Date: 2026-01-06 14:33:04.593293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0085f6ca55d'
down_revision: Union[str, Sequence[str], None] = '4f5d681548db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_rules',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_domains', sa.Text(), nullable=False),
    sa.Column('scariness_level', sa.Integer(), nullable=False),
    sa.Column('content_rating', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    op.create_index(op.f('ix_inference_rules_rule_key'), 'inference_rules', ['rule_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inference_rules_rule_key'), table_name='inference_rules')
    op.drop_table('inference_rules')
    # ### end Alembic commands ###
